#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
MAP="$ROOT/wiki/SOURCE_MAP.tsv"
WIKI_DIR="$ROOT/wiki"
CHECK_ONLY=0

if [ "${1:-}" = "--check" ]; then
  CHECK_ONLY=1
elif [ "$#" -gt 0 ]; then
  echo "usage: $0 [--check]" >&2
  exit 2
fi

if [ ! -f "$MAP" ]; then
  echo "error: missing wiki source map: $MAP" >&2
  exit 1
fi

tmp_dir="$(mktemp -d "${TMPDIR:-/tmp}/l0_wiki_sync.XXXXXX")"
trap 'rm -rf "$tmp_dir"' EXIT

home_tmp="$tmp_dir/Home.md"
{
  echo "<!-- Generated by scripts/sync_wiki.sh. Do not edit manually. -->"
  echo
  echo "# L0 Wiki"
  echo
  echo "I use this wiki mirror as a fast navigation layer over my canonical docs in \`docs/\`."
  echo
  echo "## Pages"
} > "$home_tmp"

page_count=0
while IFS='|' read -r wiki_page docs_src; do
  [ -n "$wiki_page" ] || continue
  case "$wiki_page" in
    \#*) continue ;;
  esac

  src="$ROOT/$docs_src"
  dst="$WIKI_DIR/$wiki_page"
  gen="$tmp_dir/$wiki_page"

  if [ ! -f "$src" ]; then
    echo "error: mapped source doc not found: $docs_src" >&2
    exit 1
  fi

  {
    echo "<!-- Generated by scripts/sync_wiki.sh from $docs_src. Do not edit manually. -->"
    echo
    cat "$src"
  } > "$gen"

  if [ "$CHECK_ONLY" -eq 1 ]; then
    if [ ! -f "$dst" ] || ! cmp -s "$gen" "$dst"; then
      echo "FAIL: wiki drift for $wiki_page (source $docs_src)"
      exit 1
    fi
  else
    if [ ! -f "$dst" ] || ! cmp -s "$gen" "$dst"; then
      cp "$gen" "$dst"
    fi
  fi

  page_count=$((page_count + 1))
  page_label="${wiki_page%.md}"
  echo "- [$page_label]($wiki_page)" >> "$home_tmp"
done < "$MAP"

if [ "$page_count" -lt 10 ]; then
  echo "error: wiki source map unexpectedly small"
  exit 1
fi

if [ "$CHECK_ONLY" -eq 1 ]; then
  if [ ! -f "$WIKI_DIR/Home.md" ] || ! cmp -s "$home_tmp" "$WIKI_DIR/Home.md"; then
    echo "FAIL: wiki drift for Home.md"
    exit 1
  fi
else
  if [ ! -f "$WIKI_DIR/Home.md" ] || ! cmp -s "$home_tmp" "$WIKI_DIR/Home.md"; then
    cp "$home_tmp" "$WIKI_DIR/Home.md"
  fi
fi

echo "ok"
