#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
MAP="$ROOT/wiki/SOURCE_MAP.tsv"
WIKI_DIR="$ROOT/wiki"
CHECK_ONLY=0

if [ "${1:-}" = "--check" ]; then
  CHECK_ONLY=1
elif [ "$#" -gt 0 ]; then
  echo "usage: $0 [--check]" >&2
  exit 2
fi

if [ ! -f "$MAP" ]; then
  echo "error: missing wiki source map: $MAP" >&2
  exit 1
fi

tmp_dir="$(mktemp -d "${TMPDIR:-/tmp}/l0_wiki_sync.XXXXXX")"
trap 'rm -rf "$tmp_dir"' EXIT

home_tmp="$tmp_dir/Home.md"
sidebar_tmp="$tmp_dir/_Sidebar.md"
lang_list="$tmp_dir/lang.list"
tool_list="$tmp_dir/tool.list"
contract_list="$tmp_dir/contract.list"
planning_list="$tmp_dir/planning.list"
misc_list="$tmp_dir/misc.list"
touch "$lang_list" "$tool_list" "$contract_list" "$planning_list" "$misc_list"

{
  echo "<!-- Generated by scripts/sync_wiki.sh. Do not edit manually. -->"
  echo
  echo "# L0 Wiki"
  echo
  echo "I use this wiki as the readable entry point for my canonical documentation in \`docs/\`."
  echo
  echo "## Quick Start"
  echo
  echo '```sh'
  echo "./bin/l0c verify docs/examples/01_arithmetic_add_wrap.l0"
  echo "./bin/l0c build docs/examples/01_arithmetic_add_wrap.l0 /tmp/l0_wiki_quick.img"
  echo "./bin/l0c run /tmp/l0_wiki_quick.img 5 8"
  echo '```'
  echo
  echo "## Navigation"
} > "$home_tmp"

page_count=0
while IFS='|' read -r wiki_page docs_src; do
  [ -n "$wiki_page" ] || continue
  case "$wiki_page" in
    \#*) continue ;;
  esac

  src="$ROOT/$docs_src"
  dst="$WIKI_DIR/$wiki_page"
  gen="$tmp_dir/$wiki_page"

  if [ ! -f "$src" ]; then
    echo "error: mapped source doc not found: $docs_src" >&2
    exit 1
  fi

  {
    echo "<!-- Generated by scripts/sync_wiki.sh from $docs_src. Do not edit manually. -->"
    echo
    cat "$src"
  } > "$gen"

  if [ "$CHECK_ONLY" -eq 1 ]; then
    if [ ! -f "$dst" ] || ! cmp -s "$gen" "$dst"; then
      echo "FAIL: wiki drift for $wiki_page (source $docs_src)"
      exit 1
    fi
  else
    if [ ! -f "$dst" ] || ! cmp -s "$gen" "$dst"; then
      cp "$gen" "$dst"
    fi
  fi

  page_count=$((page_count + 1))
  page_label="${wiki_page%.md}"
  case "$wiki_page" in
    Language-Reference.md|Instruction-Set.md|How-To-Write-L0.md|Implementable-Spec.md|CLI-and-Compiler-Spec.md|LLM-Quick-Reference.md|Command-Reference.md|Examples-Catalog.md)
      echo "- [$page_label]($wiki_page)" >> "$lang_list"
      ;;
    Workflow-Reference.md|Project-Status.md)
      echo "- [$page_label]($wiki_page)" >> "$tool_list"
      ;;
    *Contracts*.md|*Schema*.md|*Policy*.md|*Readiness*.md|Deterministic-Builds.md|Differential-Testing.md|Fuzz-Stress.md|Performance-Baselines.md|Error-Model.md|Release-Pipeline.md)
      echo "- [$page_label]($wiki_page)" >> "$contract_list"
      ;;
    Documentation-Roadmap.md|Coverage-Matrix.md)
      echo "- [$page_label]($wiki_page)" >> "$planning_list"
      ;;
    *)
      if [ "$wiki_page" != "SOURCE_MAP.tsv" ]; then
        echo "- [$page_label]($wiki_page)" >> "$misc_list"
      fi
      ;;
  esac
done < "$MAP"

if [ "$page_count" -lt 10 ]; then
  echo "error: wiki source map unexpectedly small"
  exit 1
fi

{
  echo
  echo "### Language and Authoring"
  cat "$lang_list"
  echo
  echo "### Tooling and Operations"
  cat "$tool_list"
  echo
  echo "### Contracts and Compatibility"
  cat "$contract_list"
  echo
  echo "### Planning and Coverage"
  cat "$planning_list"
  if [ -s "$misc_list" ]; then
    echo
    echo "### Other"
    cat "$misc_list"
  fi
} >> "$home_tmp"

{
  echo "<!-- Generated by scripts/sync_wiki.sh. Do not edit manually. -->"
  echo
  echo "## L0 Wiki"
  echo
  echo "- [Home](Home)"
  echo
  echo "### Language"
  cat "$lang_list"
  echo
  echo "### Tooling"
  cat "$tool_list"
  echo
  echo "### Contracts"
  cat "$contract_list"
  echo
  echo "### Planning"
  cat "$planning_list"
} > "$sidebar_tmp"

if [ "$CHECK_ONLY" -eq 1 ]; then
  if [ ! -f "$WIKI_DIR/Home.md" ] || ! cmp -s "$home_tmp" "$WIKI_DIR/Home.md"; then
    echo "FAIL: wiki drift for Home.md"
    exit 1
  fi
  if [ ! -f "$WIKI_DIR/_Sidebar.md" ] || ! cmp -s "$sidebar_tmp" "$WIKI_DIR/_Sidebar.md"; then
    echo "FAIL: wiki drift for _Sidebar.md"
    exit 1
  fi
else
  if [ ! -f "$WIKI_DIR/Home.md" ] || ! cmp -s "$home_tmp" "$WIKI_DIR/Home.md"; then
    cp "$home_tmp" "$WIKI_DIR/Home.md"
  fi
  if [ ! -f "$WIKI_DIR/_Sidebar.md" ] || ! cmp -s "$sidebar_tmp" "$WIKI_DIR/_Sidebar.md"; then
    cp "$sidebar_tmp" "$WIKI_DIR/_Sidebar.md"
  fi
fi

echo "ok"
